#!/usr/bin/env sh

#Rodar o PHPStan
./vendor/bin/phpstan
if [ $? -ne 0 ]; then
    echo "Opa! Deu ruim aqui com PHPStan. Arrume antes de continuar... 😉";
    exit 1;
fi;


# Formatar cada arquivo alterado usando o Laravel Pint
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$") || true

for FILE in $STAGED_FILES
do
    ./vendor/bin/pint "${FILE}"
    git add "${FILE}"
    echo "git add '${FILE}'"
done;

exit 0;
